Repository StreisandEffect/streisand, pull requests merged in 2018-07, with the labels that each got.

#1387 Add dirmngr to @hamidzr's gpg-agent patch in #1335
  playbooks/roles/gpg/tasks/main.yml
Labels: area/ansible, area/provisioning

#1398 Fix "No valid certificates available for authentication" error for iOS OpenConnect
  playbooks/roles/openconnect/templates/client.mobileconfig.j2
  playbooks/roles/openconnect/templates/config.j2
Labels: area/openconnect, client/ios, kind/bug

#1400 Ensure VPN profile names fit in Linux network device names
  playbooks/roles/common/tasks/main.yml
  playbooks/roles/common/vars/main.yml
Labels: area/host, area/wireguard, kind/bug

#1395 When checking syntax, don't search inside the venv directory
  tests/shellcheck.sh
  tests/yamlcheck.sh
Labels: kind/bug
